apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - vault
  selector:
    matchLabels:
      app: vault
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
